name: [dry-run] Auto deploy the Angular App to GitHub Pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          sudo yarn onboard
          yarn
          sudo yarn build:gh-pages --dry-run
