name: Auto deploy the Angular App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          yarn
          yarn build:gh-pages --name="Deploy Bot" --email=kazokuwomamorou@gmail.com